spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/dailyhub?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234
  freemarker:
    suffix: .ftl
    settings:
      classic_compatible: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    port: 6379
    database: 0
    host: localhost
    password:
wechat:
  mpAddId: wxa7d7b80c743dcb57
  mpAppSecret: 1fa13d3b029132f0d1b5593d2daa78cb
  token: 1234
